name: Prebuild
on:
  workflow_dispatch:
jobs:
  prebuild:
    strategy:
      matrix:
        node: [20]
        os: [ubuntu-22.04, macos-12, macos-14, windows-2022]
        include:
        - os: ubuntu-22.04
          artifact: linux-x64
        - os: macos-12
          artifact: darwin-x64
        - os: macos-14
          artifact: darwin-arm64
        - os: windows-2022
          artifact: win32-x64
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
    - run: npm install -g bare-runtime bare-dev
    - run: npm install
    - run: bare-dev install
    - uses: actions/upload-artifact@v4
      with:
        name: prebuilds-${{ matrix.artifact }}
        path: prebuilds/*
