name: Prebuild
on:
  workflow_dispatch:
jobs:
  prebuild:
    strategy:
      matrix:
        node: [16]
        os: [ubuntu-22.04, macos-12, macos-14, windows-2022]
        include:
        - os: ubuntu-22.04
          container: ghcr.io/holepunchto/prebuild-linux
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
    - run: npm upgrade -g npm
    - run: npm install -g bare-runtime bare-dev
    - run: npm install
    - run: bare-dev install
    - uses: actions/upload-artifact@v3
      with:
        name: prebuilds
        path: prebuilds/*
